language: shell
os: linux

services:
  - docker

env:
  global:
    - MAKEFLAGS="-j 2"
  jobs:
    - TEST_OS=xenial
#    - TEST_OS=bionic

before_install:
  - docker pull rstudio/shinyapps-package-dependencies

script:
  - make test-all-$TEST_OS
